### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by Lapixx** [Lapixx/zzz#2]
Style sheets:

```scss
/**
 * Basic styling
 */
body {
    color: $text-color;
    background-color: $background-color;
}

/**
 * Set `margin-bottom` to maintain vertical rhythm
 */
h1, h2, h3, h4, h5, h6,
p, blockquote, pre,
ul, ol, dl, figure,
%vertical-rhythm {
    margin-bottom: $spacing-unit / 2;
}


div.highlight-a {

    #contact { text-decoration: underline; }

    #contact.small { font-size: smaller !important; }

   /* ---------- Generic ---------- */
   .gd    { color: #aa0000 } // Generic.Deleted
   .gd .x {} // Generic.Deleted.Specific
   .gi    { color: #00aa00 } // Generic.Inserted
}
```

HTML:

```html
<article class="post" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">{{ page.title }}</h1>
    <p class="post-meta">
        &mdash; hello there!
    </p>
    <hr/>
  </header>

  <!-- actual content starts here -->

  <div class="post-content" itemprop="articleBody">
    <button value="Content" />
  </div>

</article>
```

NodeJS:

```js
// dependencies
const KndExceptions = require("konnektid-exceptions");

/**
 * Adds a new atendee to the event
 * @param   {url}          uri            url to a resource linked to the event
 * @returns {VEvent}                      the event for chaining
 */
VEvent.prototype.attendee = function addAttendee (uri, name, status) {

    if (!uri.match(/(www)?\.[a-zA-Z]+\.[a-zA-z]{2,4}/))
        throw new Error("A valid URI is required: " + uri);

    // validation ok
    this._attendees.push({
        uri    :  uri,
        cname  :  name,
        status :  status || Status.UNKNOWN
    });

    return this;

    let message = `hello, ${firstname}!`;

    // validate the parameters
    validate(params.filter(p => p.length < 5));

    // generate a secure random token when needed
    var token = params.token && KndCrypto.token.generate();

    const RAD_2 = 3.14 * 5 * token.toDecimal("HEX");
    let RAD = RAD_2 - (token * 2);

    // return the action data
    return {
        token: token,
        service: params.service,
    };
};
```

```py
def letsDoThis(__class__, yourName):
    print("hello world")
    return 5
```
